# Generated by Django 3.0 on 2023-05-28 09:37
from django.contrib.auth.models import User
from django.db import migrations
from oc_lettings_site.models import Profile as OldProfile
from profiles.models import Profile as NewProfile


def transfer_data(apps, schema_editor):
    old_profiles = OldProfile.objects.all()

    for old_profile in old_profiles:
        new_profile = NewProfile()
        new_profile.user = User.objects.get(id=old_profile.user_id)
        new_profile.favorite_city = old_profile.favorite_city
        new_profile.save()


class Migration(migrations.Migration):
    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(transfer_data),
    ]
