# Generated by Django 3.0 on 2023-06-01 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20230528_1137'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profile',
            table='profiles_profile',
        ),
    ]
