# Generated by Django 3.0 on 2023-05-28 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oc_lettings_site', '0001_initial'),
        ('lettings', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            """
            -- Copiez toutes les données de oc_lettings_site_address vers lettings_address
            INSERT INTO lettings_address SELECT * FROM oc_lettings_site_address;
            """
        ),
        migrations.RunSQL(
            """
            -- Copiez toutes les données de oc_lettings_site_letting vers lettings_letting
            INSERT INTO lettings_letting SELECT * FROM oc_lettings_site_letting;
            """
        ),
    ]

