version: 2.1

jobs:
  build_test:
    docker:
      - image: circleci/python:3.10
    environment:
      PIPENV_VENV_IN_PROJECT: true

    steps:
      - checkout
      - run: echo "Building the project"
      - run:
          name: Install pipenv
          command: |
            pip install pipenv
            pipenv install --deploy --system

      - run: echo "Running tests"
      - run:
          name: Run tests
          command: pipenv run pytest

  containerize:
    docker:
      - image: docker:latest
    steps:
      - checkout
      - run: echo "Running containerize"
      - run:
          name: Build Docker image
          command: |
            docker build -t oc_lettings .
            docker tag oc_lettings $DOCKERHUB_USERNAME/oc_lettings:$CIRCLE_SHA1
            docker login --username $DOCKERHUB_USERNAME --password $DOCKERHUB_PASSWORD
            docker push $DOCKERHUB_USERNAME/oc_lettings:$CIRCLE_SHA1

  deploy:
    docker:
      - image: python:3.10
    steps:
      - checkout
      - run: echo "Running deploy"
      - run: docker push oc_lettings

workflows:
  build_test_deploy:
    jobs:
      - build_test
      - containerize:
          requires:
            - build_test
          filters:
            branches:
              only: main
      - deploy:
          requires:
            - containerize
          filters:
            branches:
             only: main
