version: 2.1

jobs:
  contenairize:
    docker:
      - image: docker:latest
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Build Docker image
          command: |
            docker build -t oc_lettings .
            docker tag oc_lettings $DOCKERHUB_USERNAME/oc_lettings:$CIRCLE_SHA1
            docker login --username $DOCKERHUB_USERNAME --password $DOCKERHUB_PASSWORD
            docker push $DOCKERHUB_USERNAME/oc_lettings:$CIRCLE_SHA1

workflows:
  contenairize_workflow:
    jobs:
      - contenairize
