version: 2.1

jobs:
  build_test:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - run:
          name: Install pipenv
          command: |
            pip install pipenv
            pip install -r requirements.txt
      - run:
          name: Run tests
          command: pipenv run pytest

  containerize:
    docker:
      - image: docker:latest
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Build Docker image
          command: |
            docker build -t oc_lettings .
            docker tag oc_lettings registry.heroku.com/$HEROKU_APP/web

  deploy:
    docker:
      - image: docker:latest
    steps:
      - checkout
      #- setup_remote_docker
      - run:
          name: Login to Heroku Container Registry
          command: |
            echo "$HEROKU_API_KEY" | docker login --username=$HEROKU_USERNAME --password-stdin registry.heroku.com
      - run:
          name: Push Docker image to Heroku
          command: |
            docker tag oc_lettings registry.heroku.com/$HEROKU_APP/web
            docker push registry.heroku.com/$HEROKU_APP/web
      - run:
          name: Release app on Heroku
          command: heroku container:release web --app $HEROKU_APP

workflows:
  build_test_deploy:
    jobs:
      - build_test
      - containerize
#          requires:
#            - build_test
#          filters:
#            branches:
#              only: dev_ci_cd
      - deploy:
          context:
            - heroku credentials
          requires:
            - containerize
#          filters:
#            branches:
#              only: dev_ci_cd
