version: 2.1

jobs:
  containerize:
    docker:
      - image: docker:latest
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Build Docker image
          command: |
            docker build -t oc_lettings .
            docker tag oc_lettings registry.heroku.com/$HEROKU_APP/web

workflows:
  version: 2
  containerize_workflow:
    jobs:
      - containerize
