version: 2.1

jobs:
  build_test:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - run:
          name: Install pipenv
          command: |
            pip install pipenv
            pip install -r requirements.txt
      - run:
          name: Run tests
          command: pipenv run pytest

  deploy:
    docker:
      - image: docker:latest
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Build Docker image
          command: |
            docker build -t oc_lettings .
            docker tag oc_lettings registry.heroku.com/tp13-gma/web
      - run:
          name: Deploy to Heroku
          command: |
            echo "$HEROKU_API_KEY" | docker login --username=_ --password-stdin registry.heroku.com
            docker push registry.heroku.com/tp13-gma/web
            heroku container:release web --app tp13-gma

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build_test
      - deploy:
          requires:
            - build_test
          filters:
            branches:
              only: main

# Définition du contexte CircleCI pour les variables d'environnement
contexts:
  - heroku credentials
