version: 2.1

jobs:
  build_test:
    docker:
      - image: circleci/python:3.10
        environment:
          PIPENV_VENV_IN_PROJECT: true

    steps:
      - checkout
      - run: echo "Building the project"
      - run:
          name: Install pipenv
          command: |
            pip install pipenv
      #- run: 
      #    command: |
      #      ls -al
      #      cat /home/circleci/project/requirements.txt

      - run:
          name: Install Dependencies
          command: |
            pipenv install -r requirements.txt


      - run: echo "Building testing"
      - run:
          name: Run building test
          command: pipenv run pytest

  containerize:
    docker:
      - image: docker:latest
    steps:
      - checkout
      - run: echo "Running containerize"
      - run: echo docker build -t oc_lettings .

  deploy:
    docker:
      - image: python:3.10
    steps:
      - checkout
      - run: echo "Running deploy"
      - run: docker push oc_lettings


workflows:
    build_test_deploy:
      jobs:
        - build_test
        - containerize:
            requires:
              - build_test
            filters:
              branches:
                only: main
        - deploy:
            requires:
              - containerize
            filters:
              branches:
                only: main