# Generated by Django 3.0 on 2023-05-29 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oc_lettings_site', '0002_auto_20230528_1132'),
    ]

    operations = [
        migrations.RunSQL("DROP TABLE IF EXISTS oc_lettings_site_address;"),
        migrations.RunSQL("DROP TABLE IF EXISTS oc_lettings_site_letting;"),
        migrations.RunSQL("DROP TABLE IF EXISTS oc_lettings_site_profil;"),
    ]
